import 'package:thingsboard_app/locator.dart';
import 'package:thingsboard_app/modules/smarthome/home/domain/entities/smarthome_device.dart';
import 'package:thingsboard_app/thingsboard_client.dart';
import 'package:thingsboard_app/utils/services/smarthome/device_control_service.dart';
import 'package:thingsboard_app/utils/services/tb_client_service/i_tb_client_service.dart';

class ProvisioningService {
  ProvisioningService()
      : _client = getIt<ITbClientService>().client,
        _control = DeviceControlService();

  final ThingsboardClient _client;
  final DeviceControlService _control;

  static const _containsRelation = 'Contains';

  // ─── Gateway discovery ────────────────────────────────────────────────────

  /// Finds gateway devices. Searches:
  /// 1. Direct Home→Device Contains relations
  /// 2. If none found, all customer devices (gateways may not be assigned to home)
  Future<List<SmarthomeDevice>> fetchGatewayDevices(String homeId) async {
    // 1. Check direct Home→Device relations first
    final relations = await _client.getEntityRelationService().findByFrom(
          AssetId(homeId),
          relationType: _containsRelation,
        );
    final deviceIds = relations
        .where((r) => r.to.entityType == EntityType.DEVICE)
        .map((r) => r.to.id!)
        .toList();

    List<Device> allDevices;
    if (deviceIds.isNotEmpty) {
      allDevices =
          await _client.getDeviceService().getDevicesByIds(deviceIds);
    } else {
      // 2. No devices under home — search all customer devices
      final user = await _client.getUserService().getUser();
      final customerId = user.customerId?.id;
      if (customerId == null) return [];
      final page = await _client.getDeviceService().getCustomerDevices(
            customerId,
            PageLink(100),
          );
      allDevices = page.data;
    }

    return allDevices
        .where((d) => _isGateway(d))
        .map(SmarthomeDevice.fromDevice)
        .toList();
  }

  /// Checks if a device is a gateway using TB's additionalInfo flag first,
  /// then falls back to type name matching.
  bool _isGateway(Device d) {
    final info = d.additionalInfo;
    if (info != null) {
      final gw = info['gateway'];
      if (gw == true || gw == 'true') return true;
    }
    return d.type.toLowerCase().contains('gateway');
  }

  // ─── Pairing RPC ─────────────────────────────────────────────────────────

  /// Sends start_pairing RPC to gateway (one-way, fire-and-forget).
  /// Uses one-way RPC so it doesn't block waiting for gateway response.
  Future<void> startPairing(
    String gatewayId, {
    String? deviceType,
    int timeoutSeconds = 60,
  }) async {
    await _control.sendOneWayRpc(
      gatewayId,
      'start_pairing',
      {
        if (deviceType != null) 'device_type': deviceType,
        'timeout_seconds': timeoutSeconds,
      },
    );
  }

  /// Sends stop_pairing RPC to gateway (one-way, fire-and-forget).
  Future<void> stopPairing(String gatewayId) async {
    await _control.sendOneWayRpc(gatewayId, 'stop_pairing', {});
  }

  // ─── Sub-device discovery ─────────────────────────────────────────────────

  /// Returns all sub-devices currently registered under the gateway.
  /// ThingsBoard creates a Contains relation from gateway to sub-device
  /// when the gateway connects the device via v1/gateway/connect.
  Future<List<SmarthomeDevice>> fetchSubDevices(String gatewayId) async {
    final relations = await _client.getEntityRelationService().findByFrom(
          DeviceId(gatewayId),
          relationType: _containsRelation,
        );
    final deviceIds = relations
        .where((r) => r.to.entityType == EntityType.DEVICE)
        .map((r) => r.to.id!)
        .toList();
    if (deviceIds.isEmpty) return [];
    final devices = await _client.getDeviceService().getDevicesByIds(deviceIds);
    return devices.map(SmarthomeDevice.fromDevice).toList();
  }

  // ─── Claiming ─────────────────────────────────────────────────────────────

  /// Claims a direct device (non-sub-device) for the current customer.
  /// [deviceName] is what's registered in TB (e.g. "dev_{mac}").
  /// [secretKey] is the 6-char key generated by the device.
  ///
  /// Throws if claiming fails or the device is already claimed.
  /// Returns the claimed device id on success.
  Future<String> claimDevice(String deviceName, String secretKey) async {
    final result = await _client
        .getDeviceService()
        .claimDevice(deviceName, ClaimRequest(secretKey: secretKey));
    if (result.response != ClaimResponse.SUCCESS) {
      throw Exception('Claiming thất bại: ${result.response.toShortString()}');
    }
    return result.device.id!.id!;
  }

  // ─── Room assignment ──────────────────────────────────────────────────────

  /// Creates a Contains relation from [homeId] to [deviceId].
  Future<void> assignToHome(String deviceId, String homeId) async {
    await _client.getEntityRelationService().saveRelation(
          EntityRelation(
            from: AssetId(homeId),
            to: DeviceId(deviceId),
            type: _containsRelation,
          ),
        );
  }

  /// Creates a Contains relation from [roomId] to [deviceId].
  Future<void> assignToRoom(String deviceId, String roomId) async {
    await _client.getEntityRelationService().saveRelation(
          EntityRelation(
            from: AssetId(roomId),
            to: DeviceId(deviceId),
            type: _containsRelation,
          ),
        );
  }
}
