import 'package:flutter/foundation.dart';
import 'package:thingsboard_app/locator.dart';
import 'package:thingsboard_app/modules/smarthome/home/domain/entities/smarthome_device.dart';
import 'package:thingsboard_app/modules/smarthome/home/domain/entities/smarthome_home.dart';
import 'package:thingsboard_app/thingsboard_client.dart';
import 'package:thingsboard_app/utils/services/smarthome/device_control_service.dart';
import 'package:thingsboard_app/utils/services/tb_client_service/i_tb_client_service.dart';

class ProvisioningService {
  ProvisioningService()
      : _client = getIt<ITbClientService>().client,
        _control = DeviceControlService();

  final ThingsboardClient _client;
  final DeviceControlService _control;

  static const _containsRelation = 'Contains';

  // ─── Gateway discovery ────────────────────────────────────────────────────

  /// Finds all gateway devices belonging to the customer.
  /// Gateways may or may not be assigned to a home, so we always search
  /// all customer devices and filter by the gateway flag.
  Future<List<SmarthomeDevice>> fetchGatewayDevices(String homeId) async {
    final user = await _client.getUserService().getUser();
    final customerId = user.customerId?.id;
    if (customerId == null) return [];
    final page = await _client.getDeviceService().getCustomerDevices(
          customerId,
          PageLink(100),
        );
    return page.data
        .where((d) => _isGateway(d))
        .map(SmarthomeDevice.fromDevice)
        .toList();
  }

  /// Checks if a device is a gateway using TB's additionalInfo flag first,
  /// then falls back to type name matching.
  bool _isGateway(Device d) {
    final info = d.additionalInfo;
    if (info != null) {
      final gw = info['gateway'];
      if (gw == true || gw == 'true') return true;
    }
    return d.type.toLowerCase().contains('gateway');
  }

  // ─── Pairing RPC ─────────────────────────────────────────────────────────

  /// Sends startScan RPC to gateway (one-way, fire-and-forget).
  /// Uses one-way RPC so it doesn't block waiting for gateway response.
  Future<void> startScan(
    String gatewayId, {
    String? deviceType,
    int timeoutSeconds = 60,
  }) async {
    await _control.sendOneWayRpc(
      gatewayId,
      'startScan',
      {
        if (deviceType != null) 'device_type': deviceType,
        'timeout_seconds': timeoutSeconds,
      },
    );
  }

  /// Sends stopScan RPC to gateway (one-way, fire-and-forget).
  Future<void> stopScan(String gatewayId) async {
    await _control.sendOneWayRpc(gatewayId, 'stopScan', {});
  }

  // ─── Sub-device discovery ─────────────────────────────────────────────────

  /// Returns all sub-devices registered under the gateway.
  /// TB may use different relation types depending on how the device was created:
  ///  - "Contains" — standard TB gateway protocol (v1/gateway/connect)
  ///  - "Created" — some gateway implementations create sub-devices this way
  /// We fetch ALL relations from gateway and filter to DEVICE entities.
  Future<List<SmarthomeDevice>> fetchSubDevices(String gatewayId) async {
    final relations = await _client.getEntityRelationService().findByFrom(
          DeviceId(gatewayId),
        );
    final deviceIds = relations
        .where((r) => r.to.entityType == EntityType.DEVICE)
        .map((r) => r.to.id!)
        .toSet() // deduplicate (same device may have multiple relation types)
        .toList();
    if (deviceIds.isEmpty) return [];
    // Chunk to avoid blowing past the URL length limit (TB packs every ID
    // into ?deviceIds=...).
    final svc = _client.getDeviceService();
    final devices = <Device>[];
    for (var i = 0; i < deviceIds.length; i += 50) {
      final end = (i + 50).clamp(0, deviceIds.length);
      devices.addAll(await svc.getDevicesByIds(deviceIds.sublist(i, end)));
    }
    return devices
        .where((d) => !_isGateway(d)) // exclude gateway-to-gateway relations
        .map(SmarthomeDevice.fromDevice)
        .toList();
  }

  // ─── Claiming ─────────────────────────────────────────────────────────────

  /// Claims a direct device (non-sub-device) for the current customer.
  /// [deviceName] is what's registered in TB (e.g. "dev_{mac}").
  /// [secretKey] is the 6-char key generated by the device.
  ///
  /// TB ClaimResponse semantics:
  ///   SUCCESS — device claimed for the first time.
  ///   CLAIMED — device was already assigned to this customer (re-claim).
  ///             TB still returns HTTP 200 with the device object — treat as success.
  ///   FAILURE — wrong secret key, claiming expired, or claimed by another customer.
  ///
  /// Returns the claimed device ID on SUCCESS or CLAIMED.
  /// Throws on FAILURE.
  /// Claims a device. TB returns HTTP 400 when device is already assigned to
  /// this customer (instead of a CLAIMED response). In that case we fall back
  /// to looking up the device by name from the customer's device list.
  Future<String> claimDevice(String deviceName, String secretKey) async {
    debugPrint('[Claim] START device="$deviceName"');

    ClaimResult? result;
    try {
      result = await _client
          .getDeviceService()
          .claimDevice(deviceName, ClaimRequest(secretKey: secretKey));
      debugPrint('[Claim] response=${result.response} id=${result.device.id?.id}');
    } catch (e) {
      debugPrint('[Claim] HTTP error (${e.runtimeType}): $e');
      // TB returns 400 when device already belongs to this customer.
      // Try to find it by name — if found, treat as already-claimed (OK).
      final fallbackId = await _findCustomerDeviceByName(deviceName);
      if (fallbackId != null) {
        debugPrint('[Claim] Fallback OK — device already in customer: $fallbackId');
        return fallbackId;
      }
      debugPrint('[Claim] Fallback failed — device not found for this customer');
      rethrow;
    }

    if (result.response == ClaimResponse.FAILURE) {
      debugPrint('[Claim] FAILURE response from TB');
      throw Exception(
        'Claiming thất bại. Kiểm tra secret key, claiming mode trên thiết bị, '
        'và thiết bị có thể đang thuộc customer khác.',
      );
    }

    debugPrint('[Claim] SUCCESS id=${result.device.id?.id}');
    return result.device.id!.id!;
  }

  /// Searches the current customer's device list for a device with exactly
  /// [deviceName]. Returns its ID or null if not found.
  Future<String?> _findCustomerDeviceByName(String deviceName) async {
    try {
      final user = await _client.getUserService().getUser();
      final customerId = user.customerId?.id;
      if (customerId == null) return null;
      final page = await _client.getDeviceService().getCustomerDevices(
            customerId,
            PageLink(20, 0, deviceName),
          );
      debugPrint('[Claim] Fallback search "$deviceName": '
          '${page.data.length} results');
      final match = page.data.where((d) => d.name == deviceName).firstOrNull;
      return match?.id?.id;
    } catch (e) {
      debugPrint('[Claim] Fallback search error: $e');
      return null;
    }
  }

  /// Returns IDs of devices that have a Contains relation FROM the home asset.
  Future<Set<String>> fetchHomeDeviceIds(String homeId) async {
    final relations = await _client.getEntityRelationService().findByFrom(
          AssetId(homeId),
        );
    return relations
        .where((r) => r.to.entityType == EntityType.DEVICE)
        .map((r) => r.to.id!)
        .toSet();
  }

  /// Returns IDs of devices that have a Contains relation FROM any room of the home.
  Future<Set<String>> fetchRoomDeviceIds(String homeId) async {
    final roomRelations = await _client.getEntityRelationService().findByFrom(
          AssetId(homeId),
          relationType: _containsRelation,
        );
    final roomIds = roomRelations
        .where((r) => r.to.entityType == EntityType.ASSET)
        .map((r) => r.to.id!)
        .toList();
    final ids = <String>{};
    for (final roomId in roomIds) {
      final rels = await _client.getEntityRelationService().findByFrom(
            AssetId(roomId),
            relationType: _containsRelation,
          );
      ids.addAll(
        rels
            .where((r) => r.to.entityType == EntityType.DEVICE)
            .map((r) => r.to.id!),
      );
    }
    return ids;
  }

  // ─── Device display name ──────────────────────────────────────────────────

  /// Reads the `name` client attribute pushed by the gateway on first connect.
  /// Returns null if the attribute is not set yet.
  Future<String?> fetchDeviceName(String deviceId) async {
    try {
      final attrs = await _client.getAttributeService().getAttributesByScope(
            DeviceId(deviceId),
            'CLIENT_SCOPE',
            ['name'],
          );
      for (final attr in attrs) {
        if (attr.getKey() == 'name') return attr.getValue()?.toString();
      }
    } catch (_) {}
    return null;
  }

  // ─── Room assignment ──────────────────────────────────────────────────────

  /// Creates a Contains relation from [homeId] to [deviceId].
  Future<void> assignToHome(String deviceId, String homeId) async {
    await _client.getEntityRelationService().saveRelation(
          EntityRelation(
            from: AssetId(homeId),
            to: DeviceId(deviceId),
            type: _containsRelation,
          ),
        );
  }

  /// Creates a Contains relation from [roomId] to [deviceId].
  Future<void> assignToRoom(String deviceId, String roomId) async {
    await _client.getEntityRelationService().saveRelation(
          EntityRelation(
            from: AssetId(roomId),
            to: DeviceId(deviceId),
            type: _containsRelation,
          ),
        );
  }

  // ─── Gateway home detection & transfer ────────────────────────────────────

  /// Returns true if [deviceId] is a gateway (TB additionalInfo flag or name).
  Future<bool> checkIsGateway(String deviceId) async {
    try {
      final device = await _client.getDeviceService().getDevice(deviceId);
      if (device == null) return false;
      return _isGateway(device);
    } catch (_) {
      return false;
    }
  }

  /// Finds the home asset that currently contains [deviceId] via a Contains
  /// relation (direct home→device or home→room→device).
  ///
  /// For gateways this is always a direct home→device relation.
  /// Returns null if the device is not assigned to any home.
  Future<SmarthomeHome?> findCurrentHome(
    String deviceId,
    List<SmarthomeHome> knownHomes,
  ) async {
    try {
      final rels = await _client.getEntityRelationService().findByTo(
            DeviceId(deviceId),
          );
      final homeIds = {for (final h in knownHomes) h.id};
      for (final rel in rels) {
        if (rel.type != _containsRelation) continue;
        if (rel.from.entityType != EntityType.ASSET) continue;
        final assetId = rel.from.id!;
        // Direct home→device relation
        if (homeIds.contains(assetId)) {
          return knownHomes.firstWhere((h) => h.id == assetId);
        }
        // Room→device: find the room's parent home
        final roomRels = await _client.getEntityRelationService().findByTo(
              AssetId(assetId),
            );
        for (final roomRel in roomRels) {
          if (roomRel.type != _containsRelation) continue;
          if (roomRel.from.entityType != EntityType.ASSET) continue;
          final parentId = roomRel.from.id!;
          if (homeIds.contains(parentId)) {
            return knownHomes.firstWhere((h) => h.id == parentId);
          }
        }
      }
    } catch (_) {}
    return null;
  }

  /// Transfers [gatewayId] and all its sub-devices to [newHomeId].
  ///
  /// Steps:
  ///  1. Collect sub-devices (via gateway→device relations).
  ///  2. For every device (gateway + sub-devices): delete all existing
  ///     ASSET Contains relations (home-level and room-level).
  ///  3. Assign all devices to [newHomeId] at home level (unassigned).
  ///
  /// Sub-devices land in the new home unassigned; the user can move them to
  /// rooms afterwards. Previous room assignments in the old home are cleared.
  Future<void> transferGatewayToHome(
    String gatewayId,
    String newHomeId,
  ) async {
    final subDevices = await fetchSubDevices(gatewayId);
    final allIds = [gatewayId, ...subDevices.map((d) => d.id)];

    // Remove all existing ASSET Contains relations for every device
    await Future.wait(allIds.map((deviceId) async {
      try {
        final rels = await _client.getEntityRelationService().findByTo(
              DeviceId(deviceId),
            );
        for (final rel in rels) {
          if (rel.type == _containsRelation &&
              rel.from.entityType == EntityType.ASSET) {
            await _client.getEntityRelationService().deleteRelation(
                  rel.from,
                  rel.type,
                  RelationTypeGroup.COMMON,
                  rel.to,
                );
          }
        }
      } catch (_) {}
    }));

    // Assign all to new home (parallel)
    await Future.wait(allIds.map((id) => assignToHome(id, newHomeId)));
  }
}
