import 'package:thingsboard_app/locator.dart';
import 'package:thingsboard_app/modules/smarthome/home/domain/entities/smarthome_device.dart';
import 'package:thingsboard_app/thingsboard_client.dart';
import 'package:thingsboard_app/utils/services/smarthome/device_control_service.dart';
import 'package:thingsboard_app/utils/services/tb_client_service/i_tb_client_service.dart';

class ProvisioningService {
  ProvisioningService()
      : _client = getIt<ITbClientService>().client,
        _control = DeviceControlService();

  final ThingsboardClient _client;
  final DeviceControlService _control;

  static const _containsRelation = 'Contains';

  // ─── Gateway discovery ────────────────────────────────────────────────────

  /// Finds all gateway devices belonging to the customer.
  /// Gateways may or may not be assigned to a home, so we always search
  /// all customer devices and filter by the gateway flag.
  Future<List<SmarthomeDevice>> fetchGatewayDevices(String homeId) async {
    final user = await _client.getUserService().getUser();
    final customerId = user.customerId?.id;
    if (customerId == null) return [];
    final page = await _client.getDeviceService().getCustomerDevices(
          customerId,
          PageLink(100),
        );
    return page.data
        .where((d) => _isGateway(d))
        .map(SmarthomeDevice.fromDevice)
        .toList();
  }

  /// Checks if a device is a gateway using TB's additionalInfo flag first,
  /// then falls back to type name matching.
  bool _isGateway(Device d) {
    final info = d.additionalInfo;
    if (info != null) {
      final gw = info['gateway'];
      if (gw == true || gw == 'true') return true;
    }
    return d.type.toLowerCase().contains('gateway');
  }

  // ─── Pairing RPC ─────────────────────────────────────────────────────────

  /// Sends start_pairing RPC to gateway (one-way, fire-and-forget).
  /// Uses one-way RPC so it doesn't block waiting for gateway response.
  Future<void> startPairing(
    String gatewayId, {
    String? deviceType,
    int timeoutSeconds = 60,
  }) async {
    await _control.sendOneWayRpc(
      gatewayId,
      'start_pairing',
      {
        if (deviceType != null) 'device_type': deviceType,
        'timeout_seconds': timeoutSeconds,
      },
    );
  }

  /// Sends stop_pairing RPC to gateway (one-way, fire-and-forget).
  Future<void> stopPairing(String gatewayId) async {
    await _control.sendOneWayRpc(gatewayId, 'stop_pairing', {});
  }

  // ─── Sub-device discovery ─────────────────────────────────────────────────

  /// Returns all sub-devices registered under the gateway.
  /// TB may use different relation types depending on how the device was created:
  ///  - "Contains" — standard TB gateway protocol (v1/gateway/connect)
  ///  - "Created" — some gateway implementations create sub-devices this way
  /// We fetch ALL relations from gateway and filter to DEVICE entities.
  Future<List<SmarthomeDevice>> fetchSubDevices(String gatewayId) async {
    final relations = await _client.getEntityRelationService().findByFrom(
          DeviceId(gatewayId),
        );
    final deviceIds = relations
        .where((r) => r.to.entityType == EntityType.DEVICE)
        .map((r) => r.to.id!)
        .toSet() // deduplicate (same device may have multiple relation types)
        .toList();
    if (deviceIds.isEmpty) return [];
    final devices = await _client.getDeviceService().getDevicesByIds(deviceIds);
    return devices
        .where((d) => !_isGateway(d)) // exclude gateway-to-gateway relations
        .map(SmarthomeDevice.fromDevice)
        .toList();
  }

  // ─── Claiming ─────────────────────────────────────────────────────────────

  /// Claims a direct device (non-sub-device) for the current customer.
  /// [deviceName] is what's registered in TB (e.g. "dev_{mac}").
  /// [secretKey] is the 6-char key generated by the device.
  ///
  /// Throws if claiming fails or the device is already claimed.
  /// Returns the claimed device id on success.
  Future<String> claimDevice(String deviceName, String secretKey) async {
    final result = await _client
        .getDeviceService()
        .claimDevice(deviceName, ClaimRequest(secretKey: secretKey));
    if (result.response != ClaimResponse.SUCCESS) {
      throw Exception('Claiming thất bại: ${result.response.toShortString()}');
    }
    return result.device.id!.id!;
  }

  /// Returns IDs of devices that have a Contains relation FROM the home asset.
  Future<Set<String>> fetchHomeDeviceIds(String homeId) async {
    final relations = await _client.getEntityRelationService().findByFrom(
          AssetId(homeId),
        );
    return relations
        .where((r) => r.to.entityType == EntityType.DEVICE)
        .map((r) => r.to.id!)
        .toSet();
  }

  /// Returns IDs of devices that have a Contains relation FROM any room of the home.
  Future<Set<String>> fetchRoomDeviceIds(String homeId) async {
    final roomRelations = await _client.getEntityRelationService().findByFrom(
          AssetId(homeId),
          relationType: _containsRelation,
        );
    final roomIds = roomRelations
        .where((r) => r.to.entityType == EntityType.ASSET)
        .map((r) => r.to.id!)
        .toList();
    final ids = <String>{};
    for (final roomId in roomIds) {
      final rels = await _client.getEntityRelationService().findByFrom(
            AssetId(roomId),
            relationType: _containsRelation,
          );
      ids.addAll(
        rels
            .where((r) => r.to.entityType == EntityType.DEVICE)
            .map((r) => r.to.id!),
      );
    }
    return ids;
  }

  // ─── Room assignment ──────────────────────────────────────────────────────

  /// Creates a Contains relation from [homeId] to [deviceId].
  Future<void> assignToHome(String deviceId, String homeId) async {
    await _client.getEntityRelationService().saveRelation(
          EntityRelation(
            from: AssetId(homeId),
            to: DeviceId(deviceId),
            type: _containsRelation,
          ),
        );
  }

  /// Creates a Contains relation from [roomId] to [deviceId].
  Future<void> assignToRoom(String deviceId, String roomId) async {
    await _client.getEntityRelationService().saveRelation(
          EntityRelation(
            from: AssetId(roomId),
            to: DeviceId(deviceId),
            type: _containsRelation,
          ),
        );
  }
}
